### ISSUE TITLE
Cannot get PyintallerGUI to work with windows 10 and python 2.7.2

### ISSUE THREAD

**Issue by Shaba1** [vsantiago113/PyInstallerGUI#3]
I posted this on youtube when you have the video demo but I did not get a response so I am posting it here again

5 days ago
I think you should remind people that your code will only work with python 3 not with python 2.7. I tried it but I get the import error.....

C:\Users\Desktop\PyInstaller\PyInstallerGUI>python pyinstallergui.py
Traceback (most recent call last):
  File "pyinstallergui.py", line 3, in <module>
    import tkinter as tk
ImportError: No module named tkinter
 
In python 2.7 the module is named Tkinter not tkinter.

After doing a find and replace I tried again.

So after doing some more research on the web I changed the first 5 lines to this

from Tkinter import *
from ttk import *
from Tkinter import messagebox
from Tkinter import font
from Tkinter import filedialog

I tried running from the command prompt again
and go this error.

C:\Users\Desktop\PyInstaller\PyInstallerGUI>

Traceback (most recent call last):
  File "PyInstallerGUI.py", line 4, in <module>
    from Tkinter import messagebox
ImportError: cannot import name messagebox

At which point I just gave up. 

If the code only works on python 3+ just give that as a warning.﻿

**Comment by vsantiago113** [comment]
Hi, did you download the latest code? I will check again I thought I had it
test in python 3.

**Comment by Shaba1** [comment]
I downloaded the code from right here on github as a zip file. BTW I was saying it does not work with PYTHON 2.7.5 not Python 3+

I only use python 2.7.5 because I have several old plugins that will not work with python 3. And I do not have a pressing need for python 3 right now.

**Comment by Shaba1** [comment]
Any answers?

**Comment by vsantiago113** [comment]
Sorry for the delay, I will look into that tonight and respond to you.

**Comment by vsantiago113** [comment]
I was checking this and yea it only works on Python 3 right now but I will change it so is compatible with Python 2 and 3.

**Comment by vsantiago113** [comment]
I made it compatible with Python 2 and 3. I apologize for the delay.

**Comment by vsantiago113** [comment]
This has been all fixed. Give it a try.

**Comment by Shaba1** [comment]
Sorry that I missed your response vsantiagol113. It got buried in my inbox. I will download the newest version from github and will let you know my results. By the way is is absolutely necessary to have the PyIntallerGUI folder unzipped to the C:\Python27\.....\lib\site packages\ folder. I have it unzipped to a folder of its own on my desktop. I was thinking maybe that might be causing the problems.

**Comment by vsantiago113** [comment]
I changed the way it works and is different from the video I have in YouTube. For this update you have to download it, just save it in your desktop and install the requirements.txt file and that should work. I am going to upload an updated video in YouTube shortly.

**Comment by Shaba1** [comment]
Ok I unzipped it to a folder on my desktop. Then I double clicked the PyInstallerGUI.py file and the interface started right up.  So at least that works. I have not tried compiling anything yet. I will wait for the new video and give you my results . And BTW Thank you very much for responding. So many open source/ freeware programmers just post things with no documentation ( or what they THINK is documentation but is actually a feature list or code docs) and then just abandon the project.

**Comment by Shaba1** [comment]
Please Please Please let me know when you make the new video. I do not want to even try the new version that works with python 2.7 until you do post it. I am afraid of messing something up 🗡

**Comment by vsantiago113** [comment]
Is already on YouTube.
